"""empty message

Revision ID: 3602f0ed8ec7
Revises: 0eda75573fc7
Create Date: 2025-01-05 19:14:08.255727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3602f0ed8ec7'
down_revision: Union[str, None] = '0eda75573fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'brand_images', ['id'])
    op.create_unique_constraint(None, 'brands', ['id'])
    op.create_unique_constraint(None, 'brands_to_watches', ['id'])
    op.create_unique_constraint(None, 'collections', ['id'])
    op.create_unique_constraint(None, 'collections_to_watches', ['id'])
    op.create_unique_constraint(None, 'likes', ['id'])
    op.create_unique_constraint(None, 'tags', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'watch_descriptions', ['id'])
    op.create_index('WatchImagesModel_image_type_index', 'watch_images', ['image_type'], unique=False)
    op.create_unique_constraint(None, 'watch_images', ['id'])
    op.create_unique_constraint(None, 'watches', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watches', type_='unique')
    op.drop_constraint(None, 'watch_images', type_='unique')
    op.drop_index('WatchImagesModel_image_type_index', table_name='watch_images')
    op.drop_constraint(None, 'watch_descriptions', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'likes', type_='unique')
    op.drop_constraint(None, 'collections_to_watches', type_='unique')
    op.drop_constraint(None, 'collections', type_='unique')
    op.drop_constraint(None, 'brands_to_watches', type_='unique')
    op.drop_constraint(None, 'brands', type_='unique')
    op.drop_constraint(None, 'brand_images', type_='unique')
    # ### end Alembic commands ###
