"""empty message

Revision ID: 59c6f6c890d4
Revises: 636cab1b1e8a
Create Date: 2025-01-14 18:39:49.405482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c6f6c890d4'
down_revision: Union[str, None] = '636cab1b1e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_image', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('countries_index_name', 'countries', ['name'], unique=False)
    op.drop_index('watch_images_composite_index', table_name='watch_images')
    op.drop_index('watch_images_image_type_index', table_name='watch_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('watch_images_image_type_index', 'watch_images', ['image_type'], unique=False)
    op.create_index('watch_images_composite_index', 'watch_images', ['watch_id', 'image_type'], unique=False)
    op.drop_index('countries_index_name', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
