"""empty message

Revision ID: 6864fa26e5a6
Revises: 0bd46a9533ca
Create Date: 2024-12-15 14:54:07.801968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6864fa26e5a6'
down_revision: Union[str, None] = '0bd46a9533ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_email', 'users', ['email'], unique=False)
    op.create_index('ix_phone_number', 'users', ['phone_number'], unique=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_phone_number', table_name='users')
    op.drop_index('ix_email', table_name='users')
    # ### end Alembic commands ###
