"""empty message

Revision ID: 6cba861e1c45
Revises: 5c1a4698c536
Create Date: 2024-12-25 16:03:10.630844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cba861e1c45'
down_revision: Union[str, None] = '5c1a4698c536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'brand_images', ['id'])
    op.create_unique_constraint(None, 'brands', ['id'])
    op.create_unique_constraint(None, 'brands_to_watches', ['id'])
    op.create_unique_constraint(None, 'collections', ['id'])
    op.create_unique_constraint(None, 'collections_to_watches', ['id'])
    op.create_unique_constraint(None, 'descriptions', ['id'])
    op.create_unique_constraint(None, 'likes', ['id'])
    op.create_unique_constraint(None, 'tags', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'watches', ['id'])
    op.create_unique_constraint(None, 'watches_images', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watches_images', type_='unique')
    op.drop_constraint(None, 'watches', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'likes', type_='unique')
    op.drop_constraint(None, 'descriptions', type_='unique')
    op.drop_constraint(None, 'collections_to_watches', type_='unique')
    op.drop_constraint(None, 'collections', type_='unique')
    op.drop_constraint(None, 'brands_to_watches', type_='unique')
    op.drop_constraint(None, 'brands', type_='unique')
    op.drop_constraint(None, 'brand_images', type_='unique')
    # ### end Alembic commands ###
