"""empty message

Revision ID: a8c9030a9d3a
Revises: fb2d38514eec
Create Date: 2025-01-28 19:36:36.800492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8c9030a9d3a'
down_revision: Union[str, None] = 'fb2d38514eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_images', sa.Column('brand_image_type', postgresql.ENUM('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetype', create_type=False), nullable=True))
    op.add_column('brand_images', sa.Column('brand_image_url', sa.String(length=2048), nullable=True))
    op.drop_column('brand_images', 'image_url')
    op.drop_column('brand_images', 'image_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_images', sa.Column('image_type', postgresql.ENUM('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetype', create_type=False), autoincrement=False, nullable=False))
    op.add_column('brand_images', sa.Column('image_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False))
    op.drop_column('brand_images', 'brand_image_url')
    op.drop_column('brand_images', 'brand_image_type')
    # ### end Alembic commands ###
