"""empty message

Revision ID: ae12039c1bcb
Revises: 1872d9c56e60
Create Date: 2025-01-28 17:39:13.925787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae12039c1bcb'
down_revision: Union[str, None] = '1872d9c56e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_images', sa.Column('image_type', postgresql.ENUM('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetypes', create_type=False), nullable=False))
    op.drop_column('brand_images', 'brand_image_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_images', sa.Column('brand_image_type', postgresql.ENUM('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetypes', create_type=False), autoincrement=False, nullable=False))
    op.drop_column('brand_images', 'image_type')
    # ### end Alembic commands ###
