"""empty message

Revision ID: ba6e799eaf51
Revises: 
Create Date: 2025-01-20 22:01:10.774479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6e799eaf51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('countries',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('countries_index_name', 'countries', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone_number', name='uq_phone_number')
    )
    op.create_index('ix_email', 'users', ['email'], unique=False)
    op.create_index('ix_phone_number', 'users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('watches',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=512), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('discount_percent', sa.DECIMAL(precision=5, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='watchstatus'), server_default='INACTIVE', nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name='check_valid_discount_percent'),
    sa.CheckConstraint('price >= 0', name='check_positive_price'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('brands',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collections_to_watches',
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('watch_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('collections_to_watches_index_watch_id', 'collections_to_watches', ['watch_id'], unique=False)
    op.create_table('country_images',
    sa.Column('country_id', sa.BigInteger(), nullable=False),
    sa.Column('country_image_type', sa.Enum('ICON', name='countryimagetypes'), nullable=False),
    sa.Column('country_image_url', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('watch_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('likes_index_watch_id', 'likes', ['watch_id'], unique=False)
    op.create_table('tags_to_watches',
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('watch_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('tags_to_watches_index_watch_id', 'tags_to_watches', ['watch_id'], unique=False)
    op.create_table('watch_descriptions',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('watch_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('watch_descriptions_index_watch_id', 'watch_descriptions', ['watch_id'], unique=False)
    op.create_table('watch_images',
    sa.Column('watch_image_type', sa.Enum('PLACEHOLDER', 'EXTERNAL', 'FEATURED', name='watchimagetype'), nullable=False),
    sa.Column('watch_image_url', sa.String(length=2048), nullable=False),
    sa.Column('watch_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('watch_images_index_watch_id', 'watch_images', ['watch_id'], unique=False)
    op.create_table('brand_images',
    sa.Column('brand_image_type', sa.Enum('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetypes'), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('brands_to_watches',
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('watch_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('brands_to_watches_index_watch_id', 'brands_to_watches', ['watch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('brands_to_watches_index_watch_id', table_name='brands_to_watches')
    op.drop_table('brands_to_watches')
    op.drop_table('brand_images')
    op.drop_index('watch_images_index_watch_id', table_name='watch_images')
    op.drop_table('watch_images')
    op.drop_index('watch_descriptions_index_watch_id', table_name='watch_descriptions')
    op.drop_table('watch_descriptions')
    op.drop_index('tags_to_watches_index_watch_id', table_name='tags_to_watches')
    op.drop_table('tags_to_watches')
    op.drop_index('likes_index_watch_id', table_name='likes')
    op.drop_table('likes')
    op.drop_table('country_images')
    op.drop_index('collections_to_watches_index_watch_id', table_name='collections_to_watches')
    op.drop_table('collections_to_watches')
    op.drop_table('brands')
    op.drop_table('watches')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_phone_number', table_name='users')
    op.drop_index('ix_email', table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_index('countries_index_name', table_name='countries')
    op.drop_table('countries')
    op.drop_table('collections')
    # ### end Alembic commands ###
