"""empty message

Revision ID: bb816dbcc0ce
Revises: eae532e67e6f
Create Date: 2025-01-05 19:23:31.374498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb816dbcc0ce'
down_revision: Union[str, None] = 'eae532e67e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('watch_images_composite_index', 'watch_images', ['watch_id', 'image_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('watch_images_composite_index', table_name='watch_images')
    # ### end Alembic commands ###
