"""empty message

Revision ID: c2d2b2107d9d
Revises: d95d61956588
Create Date: 2025-01-14 19:22:03.764381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d2b2107d9d'
down_revision: Union[str, None] = 'd95d61956588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('brands_to_countries_index_brands_to_country_id', table_name='brands_to_countries')
    op.create_index('brands_to_countries_index_country_id', 'brands_to_countries', ['country_id'], unique=False)
    op.create_unique_constraint(None, 'brands_to_countries', ['id'])
    op.create_unique_constraint(None, 'temp', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temp', type_='unique')
    op.drop_constraint(None, 'brands_to_countries', type_='unique')
    op.drop_index('brands_to_countries_index_country_id', table_name='brands_to_countries')
    op.create_index('brands_to_countries_index_brands_to_country_id', 'brands_to_countries', ['country_id'], unique=False)
    # ### end Alembic commands ###
