"""empty message

Revision ID: c341dbc01c3d
Revises: ae12039c1bcb
Create Date: 2025-01-28 17:40:13.397557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c341dbc01c3d'
down_revision: Union[str, None] = 'ae12039c1bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetype').create(op.get_bind())
    op.add_column('brand_images', sa.Column('image_type', postgresql.ENUM('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetype', create_type=False), nullable=True))
    op.alter_column('brand_images', 'image_url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.drop_column('brand_images', 'brand_image_type')
    sa.Enum('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetypes').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetypes').create(op.get_bind())
    op.add_column('brand_images', sa.Column('brand_image_type', postgresql.ENUM('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetypes', create_type=False), autoincrement=False, nullable=False))
    op.alter_column('brand_images', 'image_url',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    op.drop_column('brand_images', 'image_type')
    sa.Enum('LIGHT_IMAGE', 'DARK_IMAGE', 'PLACEHOLDER', name='brandimagetype').drop(op.get_bind())
    # ### end Alembic commands ###
