"""empty message

Revision ID: c4b36712ec40
Revises: b39e336f043a
Create Date: 2025-01-27 20:48:42.346805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b36712ec40'
down_revision: Union[str, None] = 'b39e336f043a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_links', sa.Column('social_username', sa.String(length=512), nullable=True))
    op.create_unique_constraint(None, 'social_links', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_links', type_='unique')
    op.drop_column('social_links', 'social_username')
    # ### end Alembic commands ###
