"""empty message

Revision ID: cdeddb60041a
Revises: c2d2b2107d9d
Create Date: 2025-01-14 23:10:13.359271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdeddb60041a'
down_revision: Union[str, None] = 'c2d2b2107d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_orm',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('temp')
    op.drop_index('brands_to_countries_index_country_id', table_name='brands_to_countries')
    op.drop_table('brands_to_countries')
    op.add_column('likes', sa.Column('watche_id', sa.BigInteger(), nullable=True))
    op.drop_index('likes_index_watch_id', table_name='likes')
    op.create_index('likes_index_user_id', 'likes', ['user_id'], unique=False)
    op.create_index('likes_index_watche_id', 'likes', ['watche_id'], unique=False)
    op.drop_constraint('likes_watch_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'watches', ['watche_id'], ['id'], ondelete='CASCADE')
    op.drop_column('likes', 'watch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('watch_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_watch_id_fkey', 'likes', 'watches', ['watch_id'], ['id'], ondelete='CASCADE')
    op.drop_index('likes_index_watche_id', table_name='likes')
    op.drop_index('likes_index_user_id', table_name='likes')
    op.create_index('likes_index_watch_id', 'likes', ['watch_id'], unique=False)
    op.drop_column('likes', 'watche_id')
    op.create_table('brands_to_countries',
    sa.Column('brand_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('country_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name='brands_to_countries_brand_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='brands_to_countries_country_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='brands_to_countries_pkey'),
    sa.UniqueConstraint('id', name='brands_to_countries_id_key')
    )
    op.create_index('brands_to_countries_index_country_id', 'brands_to_countries', ['country_id'], unique=False)
    op.create_table('temp',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='temp_pkey'),
    sa.UniqueConstraint('id', name='temp_id_key')
    )
    op.drop_table('temp_orm')
    # ### end Alembic commands ###
