"""empty message

Revision ID: eae532e67e6f
Revises: 3602f0ed8ec7
Create Date: 2025-01-05 19:20:07.675983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae532e67e6f'
down_revision: Union[str, None] = '3602f0ed8ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('WatchImagesModel_image_type_index', table_name='watch_images')
    op.create_index('watch_images_image_type_index', 'watch_images', ['image_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('watch_images_image_type_index', table_name='watch_images')
    op.create_index('WatchImagesModel_image_type_index', 'watch_images', ['image_type'], unique=False)
    # ### end Alembic commands ###
